name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.9

dependencies:
  audioplayers: ^6.6.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  google_fonts: ^8.0.2
  url_launcher: ^6.3.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
